server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Ako fajl ili folder ne postoji, preusmjeri sve na index.html (SPA fallback)
        try_files $uri $uri/ /index.html;
    }

    # Keširanje statičkih asseta radi boljih performansi
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}