export { IconCanteen } from "./IconCanteen"
export { IconEmail } from "./IconEmail"
export { IconGoogle } from "./IconGoogle"
export { IconLogout } from "./IconLogout"
export { IconMealCatalog } from "./IconMealCatalog"
export { IconMenu } from "./IconMenu"
export { IconSofascore } from "./IconSofascore"
