export { IconCanteen } from "./IconCanteen"
export { IconEmail } from "./IconEmail"
export { IconGoogle } from "./IconGoogle"
export { IconLogout } from "./IconLogout"
export { IconMenu } from "./IconMenu"
export { IconPlanner } from "./IconPlanner"
export { IconSofascore } from "./IconSofascore"
export { IconVegan } from "./IconVegan"
